//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMAN.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANHANG_CT
    {
        public long ID { get; set; }
        public long ID_BANHANG { get; set; }
        public long ID_MAHANG { get; set; }
        public Nullable<double> SL_ORDER { get; set; }
        public Nullable<double> SL_TRALAI { get; set; }
        public Nullable<double> SO_LUONG { get; set; }
        public Nullable<double> DON_GIA { get; set; }
        public Nullable<double> THANH_TIEN { get; set; }
        public Nullable<double> TIEN_GGIA { get; set; }
        public Nullable<double> TILE_GGIA { get; set; }
        public string GHI_CHU { get; set; }
        public Nullable<byte> CHOT { get; set; }
        public Nullable<bool> WEB_REFRESH { get; set; }
        public Nullable<byte> LAN_IN { get; set; }
        public Nullable<System.DateTime> NGAY_BD { get; set; }
        public Nullable<System.DateTime> NGAY_KT { get; set; }
        public string MA_LO { get; set; }
    }
}
