//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMAN.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANHANG_DATCOC
    {
        public long ID { get; set; }
        public long ID_BANHANG { get; set; }
        public byte LOAI_PM { get; set; }
        public Nullable<int> STT { get; set; }
        public string NOI_DUNG { get; set; }
        public Nullable<double> GIA_TRI { get; set; }
        public Nullable<System.DateTime> NGAY_NHAN { get; set; }
        public Nullable<System.DateTime> NGAY_TRA { get; set; }
        public string GHI_CHU { get; set; }
    }
}
