//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMAN.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANHANG_THIETLAP_TK
    {
        public long ID { get; set; }
        public byte LOAI { get; set; }
        public Nullable<int> STT { get; set; }
        public string KY_HIEU { get; set; }
        public string TK_DOANHTHU { get; set; }
        public string TK_NO { get; set; }
        public string TK_CO { get; set; }
        public string GHI_CHU { get; set; }
    }
}
