//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMAN.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANHANG_ORDER_BANPHONG
    {
        public long ID { get; set; }
        public byte LOAI_PM { get; set; }
        public long ID_BAN_PHONG { get; set; }
        public long ID_MAHANG { get; set; }
        public Nullable<double> DON_GIA { get; set; }
        public Nullable<double> SO_LUONG { get; set; }
        public Nullable<double> THANH_TIEN { get; set; }
        public string GHI_CHU { get; set; }
    }
}
