//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMAN.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANHANG_DKY_KHACH_GUIDO
    {
        public long ID { get; set; }
        public long ID_DANGKY { get; set; }
        public Nullable<short> STT { get; set; }
        public string NOI_DUNG { get; set; }
        public string GHI_CHU { get; set; }
        public Nullable<double> GIA_TRI { get; set; }
        public Nullable<long> ID_USER { get; set; }
        public Nullable<bool> TRA_DO { get; set; }
    }
}
