//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMAN.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANHANG_DKY_KHACH_DICHUNG
    {
        public long ID { get; set; }
        public long ID_DANGKY { get; set; }
        public Nullable<short> STT { get; set; }
        public string HO_TEN { get; set; }
        public string TEL { get; set; }
        public string DIA_CHI { get; set; }
        public string GIOI_TINH { get; set; }
        public string NAM_SINH { get; set; }
        public string SO_CMND { get; set; }
        public string NOI_CAP { get; set; }
        public string QUOC_TICH { get; set; }
        public string GHI_CHU { get; set; }
    }
}
