//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMAN.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANHANG_DKY_KHACH
    {
        public long ID { get; set; }
        public long ID_BANPHONG { get; set; }
        public Nullable<long> ID_KHACHHANG { get; set; }
        public Nullable<System.DateTime> NGAY_DEN { get; set; }
        public string GIO_DEN { get; set; }
        public Nullable<System.DateTime> NGAY_DI { get; set; }
        public string GIO_DI { get; set; }
        public Nullable<double> TIEN_DATCOC { get; set; }
        public Nullable<short> LOAI { get; set; }
        public string ID_USER { get; set; }
        public string GHI_CHU { get; set; }
        public string BAN_GHEP { get; set; }
    }
}
