//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMAN.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANHANG_NHAPXUAT
    {
        public long ID { get; set; }
        public byte LOAI_PM { get; set; }
        public bool LOAI_NX { get; set; }
        public Nullable<long> ID_NCC { get; set; }
        public Nullable<System.DateTime> NGAY_CT { get; set; }
        public string SO_CT { get; set; }
        public Nullable<double> THANH_TIEN { get; set; }
        public string TK_NO { get; set; }
        public string TK_CO { get; set; }
        public string GHI_CHU { get; set; }
        public string NOI_DUNG { get; set; }
        public Nullable<System.DateTime> NGAY_GIAOHANG { get; set; }
        public Nullable<long> ID_USER { get; set; }
        public Nullable<bool> KY_BANHANG { get; set; }
        public Nullable<bool> KY_QL_BANHANG { get; set; }
        public Nullable<bool> KY_KT_BANHANG { get; set; }
    }
}
