//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMAN.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANHANG
    {
        public long ID { get; set; }
        public byte LOAI_PM { get; set; }
        public System.DateTime NGAY_DONHANG { get; set; }
        public long ID_MA_BAN { get; set; }
        public byte LOAI { get; set; }
        public System.DateTime NGAY_THANHTOAN { get; set; }
        public long ID_USER { get; set; }
        public Nullable<long> ID_KHACHHANG { get; set; }
        public string SO_DONHANG { get; set; }
        public Nullable<double> TIEN_HANG { get; set; }
        public Nullable<double> TIEN_GGIA { get; set; }
        public Nullable<double> CHIET_KHAU { get; set; }
        public Nullable<double> TILE_CKHAU { get; set; }
        public Nullable<double> THUE_VAT { get; set; }
        public Nullable<double> TILE_VAT { get; set; }
        public Nullable<double> TONG_TIEN { get; set; }
        public Nullable<double> TIEN_DATCOC { get; set; }
        public string TK_TM { get; set; }
        public Nullable<double> TIEN_MAT { get; set; }
        public string TK_CNO { get; set; }
        public Nullable<double> TIEN_CNO { get; set; }
        public string TK_CARD { get; set; }
        public Nullable<long> ID_MA_CARD { get; set; }
        public Nullable<double> TIEN_CARD { get; set; }
        public string TK_VOUCHER { get; set; }
        public Nullable<long> MA_VOUCHER { get; set; }
        public Nullable<double> TIEN_VOUCHER { get; set; }
        public string TK_CO { get; set; }
        public string THOIGIAN_BD { get; set; }
        public string THOIGIAN_KT { get; set; }
        public Nullable<int> SO_KHACH { get; set; }
        public Nullable<long> ID_NHANVIEN { get; set; }
        public Nullable<double> TILE_PHIPV { get; set; }
        public Nullable<double> TIEN_PHIPV { get; set; }
        public string GHI_CHU { get; set; }
        public Nullable<bool> KHOA_SO { get; set; }
        public Nullable<double> GIAMGIA_KHAC { get; set; }
        public Nullable<bool> TRA_LAI { get; set; }
        public Nullable<byte> TINH_NGAY_GIO { get; set; }
    }
}
