//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMAN.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANHANG_BANPHONG
    {
        public long ID { get; set; }
        public byte LOAI_PM { get; set; }
        public long ID_NHOM { get; set; }
        public string MA_BAN { get; set; }
        public string TEN_BAN { get; set; }
        public Nullable<byte> STATUS { get; set; }
        public string BAN_GHEP { get; set; }
        public Nullable<bool> ORDER_THOIGIAN { get; set; }
        public Nullable<double> ORDER_BAN { get; set; }
    }
}
