//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMAN.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_CHUNG
    {
        public long ID { get; set; }
        public string CHUC_NANG { get; set; }
        public string NOI_DUNG { get; set; }
        public Nullable<double> GIA_TRI { get; set; }
    }
}
