//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMAN.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_DV_TINH
    {
        public int ID { get; set; }
        public string TEN_QUYDOI { get; set; }
        public string TEN { get; set; }
        public string LOAI { get; set; }
        public Nullable<double> HE_SO { get; set; }
        public string PHEP_TINH { get; set; }
        public Nullable<bool> DV_GOC { get; set; }
        public Nullable<double> DON_GIA { get; set; }
        public Nullable<double> DON_GIA_KHO { get; set; }
        public string MA_DT { get; set; }
        public string GHI_CHU { get; set; }
    }
}
