//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMAN.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_MA_8
    {
        public long ID { get; set; }
        public long ID_MA { get; set; }
        public Nullable<System.DateTime> NGAY_BD { get; set; }
        public Nullable<System.DateTime> NGAY_KT { get; set; }
        public Nullable<short> SO_THANG { get; set; }
        public Nullable<double> SO_LUONG { get; set; }
        public Nullable<double> DON_GIA { get; set; }
        public Nullable<double> THANH_TIEN { get; set; }
        public Nullable<double> CP_KHAC { get; set; }
        public Nullable<double> NGUYEN_GIA { get; set; }
        public Nullable<double> TILE { get; set; }
        public Nullable<bool> GIAM { get; set; }
        public string LIDO_GIAM { get; set; }
        public Nullable<short> LOAI_PHANBO { get; set; }
        public string TK_CO { get; set; }
        public string TK_NO { get; set; }
        public Nullable<long> ID_MA_DT_NO { get; set; }
        public Nullable<System.DateTime> NGAY_THANHLI { get; set; }
    }
}
