//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMAN.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_MA
    {
        public long ID { get; set; }
        public long ID_DONVI { get; set; }
        public long ID_NHOM { get; set; }
        public string SO_TK { get; set; }
        public string MA_VT { get; set; }
        public string MA_BARCODE { get; set; }
        public string TEN_VT { get; set; }
        public Nullable<long> ID_DVTINH { get; set; }
        public Nullable<bool> CHK_ALL { get; set; }
        public Nullable<bool> SU_DUNG { get; set; }
        public string GHI_CHU { get; set; }
    }
}
