//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMAN.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_MA_5_DKY
    {
        public long ID { get; set; }
        public long ID_MA { get; set; }
        public Nullable<short> NAM_TC { get; set; }
        public Nullable<double> DON_GIA { get; set; }
        public Nullable<double> SO_LUONG { get; set; }
        public Nullable<double> THANH_TIEN { get; set; }
        public Nullable<System.DateTime> NGAY_BD { get; set; }
        public Nullable<System.DateTime> NGAY_KT { get; set; }
        public string MA_SO { get; set; }
    }
}
