//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMAN.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_MA_9
    {
        public long ID { get; set; }
        public long ID_MA { get; set; }
        public Nullable<double> DON_GIA { get; set; }
        public Nullable<double> GIA_NIEMYET { get; set; }
        public Nullable<double> TILE_GGIA { get; set; }
        public Nullable<double> TIEN_GIAMGIA { get; set; }
        public Nullable<bool> SD_CHIETKHAU { get; set; }
        public Nullable<double> THUE_VAT { get; set; }
        public Nullable<bool> DINH_MUC { get; set; }
        public Nullable<byte> BAR_BEP { get; set; }
        public Nullable<bool> TICH_DIEM { get; set; }
        public Nullable<double> KHOI_LUONG { get; set; }
        public Nullable<double> THUE_TTDB { get; set; }
    }
}
