//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMAN.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_MA_9_DINHLUONG
    {
        public long ID { get; set; }
        public string TK_DOANHTHU { get; set; }
        public long ID_MA_DOANHTHU { get; set; }
        public string TK_DINHLUONG { get; set; }
        public long ID_MA_DINHLUONG { get; set; }
        public Nullable<double> DINH_LUONG { get; set; }
        public string GHI_CHU { get; set; }
    }
}
