//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMAN.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_MA_ALL_95
    {
        public long ID { get; set; }
        public long ID_MA { get; set; }
        public Nullable<double> DMTON_MIN { get; set; }
        public Nullable<double> DMTON_MAX { get; set; }
        public Nullable<bool> DVT_QUYDOI { get; set; }
        public Nullable<bool> LO_HAN_SUDUNG { get; set; }
        public byte[] IMAGE { get; set; }
    }
}
