//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMAN.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_NHOM
    {
        public long ID { get; set; }
        public long PARENT_ID { get; set; }
        public short CAP { get; set; }
        public string SO_TK { get; set; }
        public string MA_NHOM { get; set; }
        public string TEN_NHOM { get; set; }
        public Nullable<double> CHIET_KHAU { get; set; }
        public Nullable<bool> CHK_ALL { get; set; }
    }
}
