//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMAN.API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DoanhNghiepDbcontext : DbContext
    {
        public DoanhNghiepDbcontext()
            : base("name=DoanhNghiepDbcontext")
        {
        }
        public DoanhNghiepDbcontext(string ConnectStringName)
                : base(ConnectStringName)
        {
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BANHANG> BANHANGs { get; set; }
        public virtual DbSet<BANHANG_BANPHONG> BANHANG_BANPHONG { get; set; }
        public virtual DbSet<BANHANG_CARD> BANHANG_CARD { get; set; }
        public virtual DbSet<BANHANG_CT> BANHANG_CT { get; set; }
        public virtual DbSet<BANHANG_DATCOC> BANHANG_DATCOC { get; set; }
        public virtual DbSet<BANHANG_DKY_KHACH> BANHANG_DKY_KHACH { get; set; }
        public virtual DbSet<BANHANG_DKY_KHACH_DICHUNG> BANHANG_DKY_KHACH_DICHUNG { get; set; }
        public virtual DbSet<BANHANG_DKY_KHACH_GUIDO> BANHANG_DKY_KHACH_GUIDO { get; set; }
        public virtual DbSet<BANHANG_NHAPXUAT> BANHANG_NHAPXUAT { get; set; }
        public virtual DbSet<BANHANG_NHAPXUAT_CT> BANHANG_NHAPXUAT_CT { get; set; }
        public virtual DbSet<BANHANG_ORDER_BANPHONG> BANHANG_ORDER_BANPHONG { get; set; }
        public virtual DbSet<BANHANG_ORDER_THOIGIAN> BANHANG_ORDER_THOIGIAN { get; set; }
        public virtual DbSet<BANHANG_THIETLAP_TK> BANHANG_THIETLAP_TK { get; set; }
        public virtual DbSet<DM_CHUNG> DM_CHUNG { get; set; }
        public virtual DbSet<DM_DV_TINH> DM_DV_TINH { get; set; }
        public virtual DbSet<DM_MA> DM_MA { get; set; }
        public virtual DbSet<DM_MA_2_DKY> DM_MA_2_DKY { get; set; }
        public virtual DbSet<DM_MA_5_DKY> DM_MA_5_DKY { get; set; }
        public virtual DbSet<DM_MA_62_DKY> DM_MA_62_DKY { get; set; }
        public virtual DbSet<DM_MA_7> DM_MA_7 { get; set; }
        public virtual DbSet<DM_MA_7_DKY> DM_MA_7_DKY { get; set; }
        public virtual DbSet<DM_MA_8> DM_MA_8 { get; set; }
        public virtual DbSet<DM_MA_8_DKY> DM_MA_8_DKY { get; set; }
        public virtual DbSet<DM_MA_9> DM_MA_9 { get; set; }
        public virtual DbSet<DM_MA_9_DINHLUONG> DM_MA_9_DINHLUONG { get; set; }
        public virtual DbSet<DM_MA_ALL_95> DM_MA_ALL_95 { get; set; }
        public virtual DbSet<DM_NHOM> DM_NHOM { get; set; }
        public virtual DbSet<DON_VI> DON_VI { get; set; }
        public virtual DbSet<HOADON_DM_GTGT> HOADON_DM_GTGT { get; set; }
        public virtual DbSet<HOADON_HUY_TBPH> HOADON_HUY_TBPH { get; set; }
        public virtual DbSet<HOADON_MAU_KYHIEU> HOADON_MAU_KYHIEU { get; set; }
        public virtual DbSet<HOADON_QUYETDINH> HOADON_QUYETDINH { get; set; }
        public virtual DbSet<HOADON_TAIKHOAN> HOADON_TAIKHOAN { get; set; }
        public virtual DbSet<HOADON_TB_PHATHANH> HOADON_TB_PHATHANH { get; set; }
        public virtual DbSet<KEHOACH_LAMVIEC> KEHOACH_LAMVIEC { get; set; }
        public virtual DbSet<KEHOACH_NHATKY> KEHOACH_NHATKY { get; set; }
        public virtual DbSet<KH_NCC> KH_NCC { get; set; }
        public virtual DbSet<KH_NCC_CT> KH_NCC_CT { get; set; }
        public virtual DbSet<KH_NCC_DKY> KH_NCC_DKY { get; set; }
        public virtual DbSet<NHANSU> NHANSUs { get; set; }
        public virtual DbSet<NHANSU_CHAMCONG_GIO> NHANSU_CHAMCONG_GIO { get; set; }
        public virtual DbSet<NHANSU_CHAMCONG_NGAY> NHANSU_CHAMCONG_NGAY { get; set; }
        public virtual DbSet<NHANSU_GIADINH> NHANSU_GIADINH { get; set; }
        public virtual DbSet<NHANSU_HOPDONG> NHANSU_HOPDONG { get; set; }
        public virtual DbSet<NHANSU_LAMTHEM_GIO> NHANSU_LAMTHEM_GIO { get; set; }
        public virtual DbSet<NHANSU_LUONG> NHANSU_LUONG { get; set; }
        public virtual DbSet<NHANSU_LUONG_DOANHSO> NHANSU_LUONG_DOANHSO { get; set; }
        public virtual DbSet<NHANSU_LUONG_SANPHAM> NHANSU_LUONG_SANPHAM { get; set; }
        public virtual DbSet<NHANSU_PHUCAP> NHANSU_PHUCAP { get; set; }
        public virtual DbSet<NHANSU_QUATRINH_CONGTAC> NHANSU_QUATRINH_CONGTAC { get; set; }
        public virtual DbSet<NHANSU_TK_TICHHOP> NHANSU_TK_TICHHOP { get; set; }
        public virtual DbSet<NHANSU_TL_BAOHIEM> NHANSU_TL_BAOHIEM { get; set; }
        public virtual DbSet<NHANSU_TL_CHINHSACH> NHANSU_TL_CHINHSACH { get; set; }
        public virtual DbSet<NHANSU_TL_DOANHSO> NHANSU_TL_DOANHSO { get; set; }
        public virtual DbSet<NHANSU_TL_HESO_LUONG> NHANSU_TL_HESO_LUONG { get; set; }
        public virtual DbSet<NHANSU_TL_THUE_TNCN> NHANSU_TL_THUE_TNCN { get; set; }
        public virtual DbSet<NHANSU_TRINHDO> NHANSU_TRINHDO { get; set; }
        public virtual DbSet<NHATKY_PHANMEM> NHATKY_PHANMEM { get; set; }
        public virtual DbSet<PS_BANGKE_CT> PS_BANGKE_CT { get; set; }
        public virtual DbSet<PS_CCDC> PS_CCDC { get; set; }
        public virtual DbSet<PS_CHIPHI_NHAPKHO> PS_CHIPHI_NHAPKHO { get; set; }
        public virtual DbSet<PS_DOITUONG> PS_DOITUONG { get; set; }
        public virtual DbSet<PS_DULIEU_KETOAN> PS_DULIEU_KETOAN { get; set; }
        public virtual DbSet<PS_HANGHOA> PS_HANGHOA { get; set; }
        public virtual DbSet<PS_HANGHOA_59> PS_HANGHOA_59 { get; set; }
        public virtual DbSet<PS_HANGHOA_CT> PS_HANGHOA_CT { get; set; }
        public virtual DbSet<PS_NGOAITE> PS_NGOAITE { get; set; }
        public virtual DbSet<PS_THUCHI> PS_THUCHI { get; set; }
        public virtual DbSet<PS_TSCD> PS_TSCD { get; set; }
        public virtual DbSet<PS_UPLOAD> PS_UPLOAD { get; set; }
        public virtual DbSet<PS_VAT> PS_VAT { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<THIETLAP_AN_HIEN_COT> THIETLAP_AN_HIEN_COT { get; set; }
        public virtual DbSet<THIETLAP_KETCHUYEN> THIETLAP_KETCHUYEN { get; set; }
        public virtual DbSet<THIETLAP_KYHIEU_TAIKHOAN> THIETLAP_KYHIEU_TAIKHOAN { get; set; }
        public virtual DbSet<THIETLAP_THAMSO_ALL> THIETLAP_THAMSO_ALL { get; set; }
        public virtual DbSet<THIETLAP_UUTIEN_TAIKHOAN> THIETLAP_UUTIEN_TAIKHOAN { get; set; }
        public virtual DbSet<THIETLAP_XUATKHO> THIETLAP_XUATKHO { get; set; }
        public virtual DbSet<TK_SODU> TK_SODU { get; set; }
        public virtual DbSet<TK_SODU_DKY> TK_SODU_DKY { get; set; }
        public virtual DbSet<USER_LIST> USER_LIST { get; set; }
        public virtual DbSet<USER_ROLE> USER_ROLE { get; set; }
        public virtual DbSet<USER_ROLE_CT> USER_ROLE_CT { get; set; }
    }
}
