//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMAN.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON_TAIKHOAN
    {
        public long ID { get; set; }
        public long ID_MAU_HOADON { get; set; }
        public string SO_TK { get; set; }
        public string TK_VAT { get; set; }
    }
}
