//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMAN.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON_TB_PHATHANH
    {
        public long ID { get; set; }
        public long ID_MAU_HD { get; set; }
        public string NOI_DUNG { get; set; }
        public Nullable<System.DateTime> NGAY_KY { get; set; }
        public Nullable<System.DateTime> NGAY_APDUNG { get; set; }
        public Nullable<int> TU_SO { get; set; }
        public Nullable<int> DEN_SO { get; set; }
        public Nullable<int> SO_LUONG { get; set; }
        public Nullable<bool> SU_DUNG { get; set; }
        public Nullable<bool> HUY_HD { get; set; }
        public Nullable<bool> CHK_ALL { get; set; }
        public Nullable<bool> BAN_QUYEN { get; set; }
    }
}
