//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMAN.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON_MAU_KYHIEU
    {
        public long ID { get; set; }
        public long ID_LOAI_HOADON { get; set; }
        public Nullable<byte> SO_LIEN { get; set; }
        public string SO_MAU { get; set; }
        public string KY_HIEU { get; set; }
        public string MAU_FULL_HD { get; set; }
        public string DUONG_DAN { get; set; }
        public Nullable<bool> SU_DUNG { get; set; }
        public Nullable<bool> HUY_HD { get; set; }
    }
}
