//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMAN.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KEHOACH_LAMVIEC
    {
        public long ID { get; set; }
        public long ID_USER { get; set; }
        public byte LOAI_KH { get; set; }
        public string LOAI_CHUCNANG { get; set; }
        public Nullable<System.DateTime> NGAY_GS { get; set; }
        public string GIO_GS { get; set; }
        public Nullable<System.DateTime> NGAY_HH { get; set; }
        public string GIO_HH { get; set; }
        public string MUC { get; set; }
        public string NOI_DUNG { get; set; }
        public Nullable<double> GIA_TRI { get; set; }
        public Nullable<double> GIA_TRI_OK { get; set; }
        public Nullable<double> TILE { get; set; }
        public string ID_USER_NHAN { get; set; }
        public string GHI_CHU { get; set; }
        public Nullable<bool> CHI_TIET { get; set; }
        public Nullable<bool> HOAN_THANH { get; set; }
        public Nullable<bool> KY_DUYET { get; set; }
        public Nullable<bool> CHK_ALL { get; set; }
    }
}
