//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMAN.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KH_NCC
    {
        public long ID { get; set; }
        public long ID_DONVI { get; set; }
        public long ID_NHOM { get; set; }
        public string MA_KH_NCC { get; set; }
        public string MA_BARCODE { get; set; }
        public string TEN_KH_NCC { get; set; }
        public string MST { get; set; }
        public Nullable<byte> KH_NCC1 { get; set; }
        public Nullable<bool> TOCHUC_CANHAN { get; set; }
        public Nullable<long> ID_USER { get; set; }
        public string DIA_CHI { get; set; }
        public string TEL { get; set; }
        public string EMAIL { get; set; }
        public string GHI_CHU { get; set; }
        public Nullable<System.DateTime> NGAY_CS { get; set; }
        public Nullable<System.DateTime> NGAY_TAO { get; set; }
        public Nullable<bool> SU_DUNG { get; set; }
        public Nullable<bool> CHK_ALL { get; set; }
    }
}
