//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMAN.API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MasterDbcontext : DbContext
    {
        public MasterDbcontext()
            : base("name=MasterDbcontext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SERVER_HOADON_DIENTU> SERVER_HOADON_DIENTU { get; set; }
        public virtual DbSet<SERVER_ONLINE> SERVER_ONLINE { get; set; }
        public virtual DbSet<USER> USERs { get; set; }
    }
}
