//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMAN.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANSU
    {
        public long ID { get; set; }
        public long ID_DONVI { get; set; }
        public Nullable<long> ID_NHOM { get; set; }
        public string MA_NS { get; set; }
        public string MA_VANTAY { get; set; }
        public string HO_TEN { get; set; }
        public Nullable<long> ID_CHUCVU { get; set; }
        public string TEL { get; set; }
        public string EMAIL { get; set; }
        public string DIA_CHI { get; set; }
        public Nullable<System.DateTime> NGAY_SINH { get; set; }
        public Nullable<bool> GIOI_TINH { get; set; }
        public string SO_CMND { get; set; }
        public Nullable<System.DateTime> NGAY_CAP { get; set; }
        public string NOI_CAP { get; set; }
        public string MST_CANHAN { get; set; }
        public string MASO_BH { get; set; }
        public string DAN_TOC { get; set; }
        public string TON_GIAO { get; set; }
        public string QUOC_TICH { get; set; }
        public Nullable<byte> TRANG_THAI_LV { get; set; }
        public string GHI_CHU { get; set; }
        public Nullable<byte> LOAI_CHAMCONG { get; set; }
        public Nullable<byte> SU_DUNG { get; set; }
        public Nullable<bool> CHK_ALL { get; set; }
    }
}
