//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMAN.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANSU_TL_BAOHIEM
    {
        public long ID { get; set; }
        public Nullable<int> STT { get; set; }
        public string NOI_DUNG { get; set; }
        public Nullable<double> BHXH { get; set; }
        public Nullable<double> BHYT { get; set; }
        public Nullable<double> BHTN { get; set; }
        public Nullable<double> KPCD { get; set; }
        public string LOAI { get; set; }
        public Nullable<double> NAM_TC { get; set; }
    }
}
