//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMAN.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANSU_HOPDONG
    {
        public long ID { get; set; }
        public long ID_NHANVIEN { get; set; }
        public string SO_HOPDONG { get; set; }
        public Nullable<byte> LOAI_HOPDONG { get; set; }
        public Nullable<System.DateTime> NGAY_BD_HD { get; set; }
        public Nullable<System.DateTime> NGAY_KT_HD { get; set; }
        public string MOTA_CONGVIEC { get; set; }
        public Nullable<double> TIEN_THE_CHAP { get; set; }
        public Nullable<bool> SU_DUNG { get; set; }
    }
}
