//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMAN.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANSU_LUONG_DOANHSO
    {
        public long ID { get; set; }
        public long ID_NHANVIEN { get; set; }
        public byte THANG { get; set; }
        public int NAM { get; set; }
        public Nullable<int> STT { get; set; }
        public string NOI_DUNG { get; set; }
        public Nullable<double> DOANH_SO { get; set; }
        public Nullable<double> TI_LE { get; set; }
        public Nullable<double> THANH_TIEN { get; set; }
        public Nullable<long> ID_KEY { get; set; }
        public string LOAI_KEY { get; set; }
        public Nullable<double> DOANH_THU { get; set; }
        public Nullable<double> CHI_PHI { get; set; }
        public Nullable<double> LAI_VAY { get; set; }
    }
}
