//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMAN.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANSU_LAMTHEM_GIO
    {
        public long ID { get; set; }
        public long ID_NHANVIEN { get; set; }
        public byte THANG { get; set; }
        public int NAM { get; set; }
        public Nullable<double> N10 { get; set; }
        public Nullable<double> N15 { get; set; }
        public Nullable<double> N20 { get; set; }
        public Nullable<double> N30 { get; set; }
        public Nullable<double> TONG { get; set; }
        public Nullable<bool> KHOA { get; set; }
        public Nullable<byte> T7 { get; set; }
        public Nullable<byte> CN { get; set; }
    }
}
