//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMAN.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANSU_LUONG_SANPHAM
    {
        public long ID { get; set; }
        public long ID_NHANVIEN { get; set; }
        public byte THANG { get; set; }
        public int NAM { get; set; }
        public Nullable<int> STT { get; set; }
        public string NOI_DUNG { get; set; }
        public Nullable<double> DON_GIA { get; set; }
        public Nullable<double> SO_LUONG { get; set; }
        public Nullable<double> THANH_TIEN { get; set; }
        public Nullable<bool> LOAI { get; set; }
    }
}
