//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMAN.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANSU_CHAMCONG_NGAY
    {
        public long ID { get; set; }
        public long ID_NHANVIEN { get; set; }
        public byte THANG { get; set; }
        public int NAM { get; set; }
        public Nullable<byte> T7 { get; set; }
        public Nullable<byte> CN { get; set; }
        public string NGAY { get; set; }
        public string N1 { get; set; }
        public string N2 { get; set; }
        public string N3 { get; set; }
        public string N4 { get; set; }
        public string N5 { get; set; }
        public string N6 { get; set; }
        public string N7 { get; set; }
        public string N8 { get; set; }
        public string N9 { get; set; }
        public string N10 { get; set; }
        public string N11 { get; set; }
        public string N12 { get; set; }
        public string N13 { get; set; }
        public string N14 { get; set; }
        public string N15 { get; set; }
        public string N16 { get; set; }
        public string N17 { get; set; }
        public string N18 { get; set; }
        public string N19 { get; set; }
        public string N20 { get; set; }
        public string N21 { get; set; }
        public string N22 { get; set; }
        public string N23 { get; set; }
        public string N24 { get; set; }
        public string N25 { get; set; }
        public string N26 { get; set; }
        public string N27 { get; set; }
        public string N28 { get; set; }
        public string N29 { get; set; }
        public string N30 { get; set; }
        public string N31 { get; set; }
        public string TONG { get; set; }
        public Nullable<bool> KHOA { get; set; }
        public string GHI_CHU { get; set; }
    }
}
