//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMAN.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANSU_TL_CHINHSACH
    {
        public long ID { get; set; }
        public long ID_NHOM { get; set; }
        public string CHUC_NANG { get; set; }
        public Nullable<short> STT { get; set; }
        public string NOI_DUNG { get; set; }
        public Nullable<double> GIA_TRI { get; set; }
        public string GHI_CHU { get; set; }
        public string MUC_KPI { get; set; }
        public Nullable<double> KPI_KEM { get; set; }
        public Nullable<double> KPI_TRUNGBINH { get; set; }
        public Nullable<double> KPI_KHA { get; set; }
        public Nullable<double> KPI_TOT { get; set; }
    }
}
