//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMAN.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANSU_TK_TICHHOP
    {
        public long ID { get; set; }
        public Nullable<long> ID_NHOM { get; set; }
        public Nullable<bool> CHUAN { get; set; }
        public Nullable<byte> CHUCNANG { get; set; }
        public Nullable<byte> LOAI { get; set; }
        public string NOI_DUNG { get; set; }
        public string TK_NO { get; set; }
        public string TK_CO { get; set; }
        public Nullable<long> ID_MA_DT { get; set; }
        public Nullable<bool> QUANDOC { get; set; }
    }
}
