//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMAN.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANSU_QUATRINH_CONGTAC
    {
        public long ID { get; set; }
        public long ID_NHANVIEN { get; set; }
        public Nullable<System.DateTime> NGAY_BD { get; set; }
        public Nullable<System.DateTime> NGAY_KT { get; set; }
        public string DON_VI { get; set; }
        public string CHUC_VU { get; set; }
        public string MOTA_CONGVIEC { get; set; }
    }
}
