//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMAN.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHATKY_PHANMEM
    {
        public long ID { get; set; }
        public System.DateTime NGAY { get; set; }
        public string LOAI_PM { get; set; }
        public string USER_NAME { get; set; }
        public string TEN_MAYTINH { get; set; }
        public string CHUC_NANG { get; set; }
        public string NOI_DUNG { get; set; }
        public Nullable<double> GIATRI_CU { get; set; }
        public Nullable<double> GIATRI_MOI { get; set; }
    }
}
