//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMAN.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PS_BANGKE_CT
    {
        public long ID { get; set; }
        public long ID_KEY { get; set; }
        public string SOCT { get; set; }
        public Nullable<System.DateTime> NGAYCT { get; set; }
        public string NOI_DUNG { get; set; }
        public Nullable<double> THANH_TIEN { get; set; }
        public Nullable<double> TIEN_KHAC { get; set; }
        public string GHI_CHU { get; set; }
    }
}
