//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMAN.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PS_CHIPHI_NHAPKHO
    {
        public long ID { get; set; }
        public long ID_KEY { get; set; }
        public Nullable<short> STT { get; set; }
        public Nullable<System.DateTime> NGAY_CT { get; set; }
        public string SO_CT { get; set; }
        public string NOI_DUNG { get; set; }
        public Nullable<double> TIEN { get; set; }
        public string TK_CO { get; set; }
        public Nullable<long> ID_MA_DT { get; set; }
        public string GHI_CHU { get; set; }
    }
}
