//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMAN.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PS_DULIEU_KETOAN
    {
        public long ID { get; set; }
        public long ID_DONVI { get; set; }
        public long ID_USER { get; set; }
        public short NAM_TC { get; set; }
        public System.DateTime NGAY_GS { get; set; }
        public Nullable<long> STT { get; set; }
        public Nullable<short> VITRI_CT { get; set; }
        public string NHOM_CT { get; set; }
        public string SO_CT { get; set; }
        public Nullable<System.DateTime> NGAY_CT { get; set; }
        public string NOI_DUNG { get; set; }
        public string TK_NO { get; set; }
        public string SOCT_NO { get; set; }
        public string TK_CO { get; set; }
        public string SOCT_CO { get; set; }
        public Nullable<double> THANH_TIEN { get; set; }
        public Nullable<long> ID_HDKT { get; set; }
        public Nullable<bool> CHK_ALL { get; set; }
        public Nullable<bool> BANGKE_TT { get; set; }
        public Nullable<long> ID_KEP { get; set; }
        public string CHUCNANG_AUTO { get; set; }
        public Nullable<long> ID_BAR_SHOP { get; set; }
        public Nullable<bool> GIAM_DOC { get; set; }
        public Nullable<bool> KE_TOAN { get; set; }
        public Nullable<bool> THU_QUY { get; set; }
        public Nullable<bool> KY_DUYET { get; set; }
        public Nullable<bool> THU_KHO { get; set; }
        public Nullable<bool> XOA { get; set; }
        public Nullable<byte> SOLAN_IN { get; set; }
    }
}
