//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMAN.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PS_HANGHOA
    {
        public long ID { get; set; }
        public long ID_KEY { get; set; }
        public long ID_MA { get; set; }
        public Nullable<double> GIA_MUA { get; set; }
        public Nullable<double> THUE_TTDB { get; set; }
        public Nullable<double> PHI_THUE { get; set; }
        public Nullable<double> SO_LUONG { get; set; }
        public Nullable<double> DON_GIA { get; set; }
        public Nullable<double> THANH_TIEN { get; set; }
        public Nullable<double> THUE_VAT { get; set; }
        public Nullable<double> TIEN_THUE { get; set; }
        public Nullable<double> TILE_GIAMGIA { get; set; }
        public Nullable<double> TIEN_GIAMGIA { get; set; }
        public Nullable<bool> SD_CHIETKHAU { get; set; }
        public Nullable<double> TIEN_GIAM_KHAC { get; set; }
        public string TK_XUATKHO { get; set; }
        public Nullable<double> TON_KHO { get; set; }
        public Nullable<bool> QUYET_TOAN_DH { get; set; }
        public string GHI_CHU { get; set; }
    }
}
