//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMAN.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PS_HANGHOA_CT
    {
        public long ID { get; set; }
        public long ID_KEY { get; set; }
        public string TEN_HANG { get; set; }
        public string DV_TINH { get; set; }
        public Nullable<double> GIA_NIEMYET { get; set; }
        public Nullable<long> XID { get; set; }
        public string MA_LO { get; set; }
        public Nullable<System.DateTime> NGAY_BD { get; set; }
        public Nullable<System.DateTime> NGAY_HH { get; set; }
        public Nullable<double> DAI { get; set; }
        public Nullable<double> RONG { get; set; }
        public Nullable<double> CAO { get; set; }
        public Nullable<double> DON_GIA_QD { get; set; }
        public Nullable<double> SO_LUONG_QD { get; set; }
        public Nullable<double> THANH_TIEN_QD { get; set; }
        public Nullable<double> TIEN_GIAMGIA_QD { get; set; }
        public Nullable<double> TILE_QUYDOI { get; set; }
        public Nullable<bool> DVT_QUYDOI { get; set; }
        public string PHEP_TINH { get; set; }
        public string TEN_DV_TINH_QD { get; set; }
    }
}
