//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMAN.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PS_HANGHOA_59
    {
        public long ID { get; set; }
        public long ID_KEY { get; set; }
        public Nullable<long> ID_KHNCC_NV { get; set; }
        public Nullable<byte> KHNCC_NV { get; set; }
        public string HO_TEN { get; set; }
        public string DIA_CHI { get; set; }
        public string LY_DO { get; set; }
        public string CT_GOC { get; set; }
        public string GHI_CHU { get; set; }
        public string KYHIEU_HD { get; set; }
        public string MAU_HD { get; set; }
        public Nullable<byte> XOA_THAYTHE_HD { get; set; }
        public Nullable<bool> HD_CONVERT { get; set; }
        public string HT_TT { get; set; }
        public string LOAI_NGOAI_TE { get; set; }
        public Nullable<double> TI_GIA { get; set; }
        public Nullable<double> TIEN_DA_TT { get; set; }
        public Nullable<long> ID_KEY_TT { get; set; }
        public Nullable<double> TILE_CHIETKHAU { get; set; }
        public Nullable<double> TIEN_CHIETKHAU { get; set; }
        public Nullable<long> ID_HOPDONG { get; set; }
    }
}
