//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMAN.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PS_THUCHI
    {
        public long ID { get; set; }
        public long ID_KEY { get; set; }
        public Nullable<long> ID_KHNCC_NV { get; set; }
        public Nullable<byte> KHNCC_NV { get; set; }
        public string HO_TEN { get; set; }
        public string DIA_CHI { get; set; }
        public string LY_DO { get; set; }
        public string CT_GOC { get; set; }
    }
}
