//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMAN.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PS_UPLOAD
    {
        public long ID { get; set; }
        public long ID_KEY { get; set; }
        public string CHUC_NANG { get; set; }
        public Nullable<double> FILE_SIZE { get; set; }
        public Nullable<bool> CHK_UPLOAD { get; set; }
        public string FILE_ATTACH { get; set; }
        public Nullable<System.DateTime> NGAY_CREATE { get; set; }
    }
}
