//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMAN.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PS_VAT
    {
        public long ID { get; set; }
        public long ID_KEY { get; set; }
        public string MAU_HD { get; set; }
        public string KY_HIEU { get; set; }
        public string SO_HD { get; set; }
        public Nullable<System.DateTime> NGAY_HD { get; set; }
        public Nullable<long> ID_MA { get; set; }
        public string MAT_HANG { get; set; }
        public Nullable<double> DOANH_SO { get; set; }
        public Nullable<double> THUE_SUAT { get; set; }
        public Nullable<double> THUE_VAT { get; set; }
        public Nullable<double> THUE_KHAC { get; set; }
        public Nullable<double> PHI_KHAC { get; set; }
        public Nullable<byte> MUC { get; set; }
        public string GHI_CHU { get; set; }
        public Nullable<byte> XOA { get; set; }
        public Nullable<bool> VAT_IN_OUT { get; set; }
    }
}
