//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMAN.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVER_ONLINE
    {
        public long ID { get; set; }
        public string SERVER { get; set; }
        public string TEN_DATA { get; set; }
        public string USER_NAME { get; set; }
        public string PASSWORD { get; set; }
        public Nullable<System.DateTime> NGAY_BD { get; set; }
        public Nullable<System.DateTime> NGAY_HH { get; set; }
        public Nullable<int> SOLUONG_USER { get; set; }
        public string PHAN_MEM { get; set; }
        public string BQ_DATA { get; set; }
        public Nullable<short> THONG_TU { get; set; }
        public string TEN_CONGTY { get; set; }
        public string MST { get; set; }
        public string EMAIL { get; set; }
        public string TEL { get; set; }
        public string DAI_DIEN { get; set; }
        public string DIA_CHI { get; set; }
        public Nullable<double> TONG_TIEN { get; set; }
        public string GHI_CHU { get; set; }
        public Nullable<bool> SU_DUNG { get; set; }
        public Nullable<System.DateTime> DATE_CREATE { get; set; }
    }
}
