//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMAN.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVER_HOADON_DIENTU
    {
        public long ID { get; set; }
        public Nullable<long> ID_KH { get; set; }
        public string MAU_HOADON { get; set; }
        public string KYHIEU_HOADON { get; set; }
        public Nullable<long> TU_SO { get; set; }
        public Nullable<long> DEN_SO { get; set; }
        public Nullable<System.DateTime> NGAY_KY { get; set; }
        public Nullable<System.DateTime> NGAY_APDUNG { get; set; }
        public string MA_BQ { get; set; }
        public string NOI_DUNG { get; set; }
        public string SO_THONGBAO { get; set; }
        public Nullable<System.DateTime> NGAY_HOPDONG { get; set; }
        public Nullable<short> MAU_SO { get; set; }
        public Nullable<System.DateTime> NGAY_CAPNHAT { get; set; }
        public string PHIEN_BAN { get; set; }
        public Nullable<bool> DUYET { get; set; }
        public Nullable<bool> SU_DUNG { get; set; }
    }
}
