//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMAN.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THIETLAP_UUTIEN_TAIKHOAN
    {
        public long ID { get; set; }
        public string SO_TK_NO { get; set; }
        public string SO_TK_CO { get; set; }
        public string UU_TIEN { get; set; }
    }
}
