//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMAN.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THIETLAP_AN_HIEN_COT
    {
        public long ID { get; set; }
        public string TEN_FORM { get; set; }
        public string MA_COT { get; set; }
        public string TEN_COT { get; set; }
        public Nullable<bool> AN_HIEN { get; set; }
    }
}
