//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMAN.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THIETLAP_KETCHUYEN
    {
        public long ID { get; set; }
        public Nullable<short> VI_TRI { get; set; }
        public string NO_CO { get; set; }
        public string SO_TK { get; set; }
        public string NOI_DUNG { get; set; }
        public string KC_NO { get; set; }
        public string KC_CO { get; set; }
    }
}
