//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMAN.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THIETLAP_XUATKHO
    {
        public long ID { get; set; }
        public Nullable<byte> LOAI_XUATKHO { get; set; }
        public string NOI_DUNG { get; set; }
        public string TK_NO { get; set; }
        public string TK_CO { get; set; }
        public string TK_DOANHTHU { get; set; }
        public string TK_NKHO_GIACONG { get; set; }
        public string LOAI_NOCO { get; set; }
    }
}
