//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMAN.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TK_SODU_DKY
    {
        public long ID { get; set; }
        public long ID_TAIKHOAN { get; set; }
        public long ID_DONVI { get; set; }
        public Nullable<short> NAM_TC { get; set; }
        public Nullable<double> DU_NO { get; set; }
        public Nullable<double> DU_CO { get; set; }
        public string GHI_CHU { get; set; }
    
        public virtual DON_VI DON_VI { get; set; }
    }
}
