//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMAN.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TK_SODU
    {
        public long ID { get; set; }
        public long PARENT_ID { get; set; }
        public string SO_TK { get; set; }
        public string TEN_TK { get; set; }
        public string TEN_TK_ENGLISH { get; set; }
        public Nullable<byte> LOAI_TK { get; set; }
        public string DONGBO_TK { get; set; }
        public string NOI_DUNG { get; set; }
        public Nullable<bool> SU_DUNG { get; set; }
        public Nullable<short> THONG_TU { get; set; }
    }
}
