//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMAN.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_ROLE_CT
    {
        public long ID { get; set; }
        public Nullable<long> ID_ROLE { get; set; }
        public string LOAI_PM { get; set; }
        public string MA_CHUCNANG { get; set; }
        public string NOI_DUNG { get; set; }
        public Nullable<bool> TRUY_CAP { get; set; }
        public Nullable<byte> SUA { get; set; }
        public Nullable<byte> XOA { get; set; }
        public Nullable<byte> CHI_TIET { get; set; }
        public Nullable<bool> IMPORT { get; set; }
        public Nullable<bool> EXPORT { get; set; }
    }
}
