//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMAN.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public long ID { get; set; }
        public Nullable<long> PARENT_ID { get; set; }
        public string HO_TEN { get; set; }
        public string USER_NAME { get; set; }
        public string PASSWORD { get; set; }
        public string EMAIL { get; set; }
        public string TEL { get; set; }
        public Nullable<byte> ROLE_ID { get; set; }
        public Nullable<short> SU_DUNG { get; set; }
        public string MA_ID { get; set; }
        public Nullable<byte> CAP_ID { get; set; }
    }
}
